### PR TITLE
Add cooling mode

### PR DESCRIPTION
**Pull request by doctorvanmartin**
Cooling mode for hvacs with cooling capabilities, as all the Nimbus models has

### CODE REVIEW

**Comment by chomupashchuk** [comment]
Few things I've noticed:
1. Ukrainian translation is incorrect (`sensor.uk.json`), it should be "охолодження"
2. In `climate.py` method `hvac_modes` enables "cooling" if manual mode is avalable. I have a concern that HA hides modes if they are not indicated as supported and many users do not have equipment to use "cooling" option, which would raise questions and potentially tickets. it is better to be hidden if not supported. Also not sure how boiler would also react to the requests if not supported. Did you check if in REST replies some parameters indicate "cooling" support (e.g. "isCoolingSupported" parameter in self._api._ariston_data for your boiler)? I would prefer to check supported parameters dynamically, but my boiler has no "cooling" to check it (if you enable storing of files, it is in data_ariston_get_main.json)
3. In `climate.py` method `hvac_action` I see that you set active action as "cooling" based on PARAM_CH_FLAME (which is "heatRequest" from REAST reply). Did you see that during ongoing cooling this parameter is set to True? It just seems strange that Ariston would use it for heating and cooling, so just want to doublecheck.

**Comment by doctorvanmartin** [comment]
Hi Oleh,
1. Fixed
2. In the data_ariston_get_main.json are two related flags: 
    "isCoolingSupported": true,
    "isCoolingOnlySupported": false,
 but I actually don't know how to check dynamically against them. I will review the code trying to do so, as I understand what you say, and agree with.
3. Yes, I've check it. Mine is a Nimbus heat pump, and looks like the ch_flame is used when any activity of the water pump, even when the main element, the compressor is off, but still pumping water (cool or warm) to the system.

**Comment by doctorvanmartin** [comment]
There is also another flag related to issue 2, in the data_ariston_get_main.json, 
"allowedModes": [
        0,
        1,
        2,
        3, <-- thats cooling
        5
    ],

Looks that are other modes but I cant see their descriptions in the Ariston web and their json's files

**Comment by doctorvanmartin** [comment]
I've tested the changes checking properties that my machine does not have, and disabling/enabling any combination of cooling and heating modes.
I'm checking supported modes with:

if self._api._ariston_data.get("isHeatingSupported"): 
                    supported_modes.append(HVAC_MODE_HEAT)
                if self._api._ariston_data.get("isCoolingSupported"):
                    supported_modes.append(HVAC_MODE_COOL)

**Pull request merged**
